/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  JSONSchemaDto,
  JSONSchemaDto$inboundSchema,
  JSONSchemaDto$Outbound,
  JSONSchemaDto$outboundSchema,
} from "./jsonschemadto.js";

/**
 * JSON Schema for data
 */
export type DataSchema = JSONSchemaDto;

/**
 * UI Schema for rendering
 */
export type UiSchema = {};

export type ControlsMetadata = {
  /**
   * JSON Schema for data
   */
  dataSchema?: JSONSchemaDto | undefined;
  /**
   * UI Schema for rendering
   */
  uiSchema?: UiSchema | undefined;
  /**
   * Control values
   */
  values: { [k: string]: any };
};

/** @internal */
export const DataSchema$inboundSchema: z.ZodType<
  DataSchema,
  z.ZodTypeDef,
  unknown
> = JSONSchemaDto$inboundSchema;

/** @internal */
export type DataSchema$Outbound = JSONSchemaDto$Outbound;

/** @internal */
export const DataSchema$outboundSchema: z.ZodType<
  DataSchema$Outbound,
  z.ZodTypeDef,
  DataSchema
> = JSONSchemaDto$outboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DataSchema$ {
  /** @deprecated use `DataSchema$inboundSchema` instead. */
  export const inboundSchema = DataSchema$inboundSchema;
  /** @deprecated use `DataSchema$outboundSchema` instead. */
  export const outboundSchema = DataSchema$outboundSchema;
  /** @deprecated use `DataSchema$Outbound` instead. */
  export type Outbound = DataSchema$Outbound;
}

export function dataSchemaToJSON(dataSchema: DataSchema): string {
  return JSON.stringify(DataSchema$outboundSchema.parse(dataSchema));
}

export function dataSchemaFromJSON(
  jsonString: string,
): SafeParseResult<DataSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DataSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DataSchema' from JSON`,
  );
}

/** @internal */
export const UiSchema$inboundSchema: z.ZodType<
  UiSchema,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type UiSchema$Outbound = {};

/** @internal */
export const UiSchema$outboundSchema: z.ZodType<
  UiSchema$Outbound,
  z.ZodTypeDef,
  UiSchema
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UiSchema$ {
  /** @deprecated use `UiSchema$inboundSchema` instead. */
  export const inboundSchema = UiSchema$inboundSchema;
  /** @deprecated use `UiSchema$outboundSchema` instead. */
  export const outboundSchema = UiSchema$outboundSchema;
  /** @deprecated use `UiSchema$Outbound` instead. */
  export type Outbound = UiSchema$Outbound;
}

export function uiSchemaToJSON(uiSchema: UiSchema): string {
  return JSON.stringify(UiSchema$outboundSchema.parse(uiSchema));
}

export function uiSchemaFromJSON(
  jsonString: string,
): SafeParseResult<UiSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UiSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UiSchema' from JSON`,
  );
}

/** @internal */
export const ControlsMetadata$inboundSchema: z.ZodType<
  ControlsMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  dataSchema: JSONSchemaDto$inboundSchema.optional(),
  uiSchema: z.lazy(() => UiSchema$inboundSchema).optional(),
  values: z.record(z.any()),
});

/** @internal */
export type ControlsMetadata$Outbound = {
  dataSchema?: JSONSchemaDto$Outbound | undefined;
  uiSchema?: UiSchema$Outbound | undefined;
  values: { [k: string]: any };
};

/** @internal */
export const ControlsMetadata$outboundSchema: z.ZodType<
  ControlsMetadata$Outbound,
  z.ZodTypeDef,
  ControlsMetadata
> = z.object({
  dataSchema: JSONSchemaDto$outboundSchema.optional(),
  uiSchema: z.lazy(() => UiSchema$outboundSchema).optional(),
  values: z.record(z.any()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ControlsMetadata$ {
  /** @deprecated use `ControlsMetadata$inboundSchema` instead. */
  export const inboundSchema = ControlsMetadata$inboundSchema;
  /** @deprecated use `ControlsMetadata$outboundSchema` instead. */
  export const outboundSchema = ControlsMetadata$outboundSchema;
  /** @deprecated use `ControlsMetadata$Outbound` instead. */
  export type Outbound = ControlsMetadata$Outbound;
}

export function controlsMetadataToJSON(
  controlsMetadata: ControlsMetadata,
): string {
  return JSON.stringify(
    ControlsMetadata$outboundSchema.parse(controlsMetadata),
  );
}

export function controlsMetadataFromJSON(
  jsonString: string,
): SafeParseResult<ControlsMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ControlsMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ControlsMetadata' from JSON`,
  );
}
