/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * JSON Schema type
 */
export const JsonSchemaType = {
  String: "string",
  Number: "number",
  Integer: "integer",
  Boolean: "boolean",
  Array: "array",
  Object: "object",
  Null: "null",
} as const;
/**
 * JSON Schema type
 */
export type JsonSchemaType = ClosedEnum<typeof JsonSchemaType>;

/** @internal */
export const JsonSchemaType$inboundSchema: z.ZodNativeEnum<
  typeof JsonSchemaType
> = z.nativeEnum(JsonSchemaType);

/** @internal */
export const JsonSchemaType$outboundSchema: z.ZodNativeEnum<
  typeof JsonSchemaType
> = JsonSchemaType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace JsonSchemaType$ {
  /** @deprecated use `JsonSchemaType$inboundSchema` instead. */
  export const inboundSchema = JsonSchemaType$inboundSchema;
  /** @deprecated use `JsonSchemaType$outboundSchema` instead. */
  export const outboundSchema = JsonSchemaType$outboundSchema;
}
