/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  StepTypeEnum,
  StepTypeEnum$inboundSchema,
  StepTypeEnum$outboundSchema,
} from "./steptypeenum.js";

export type StepCreateDto = {
  /**
   * Name of the step
   */
  name: string;
  /**
   * Type of the step
   */
  type: StepTypeEnum;
  /**
   * Control values for the step
   */
  controlValues?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const StepCreateDto$inboundSchema: z.ZodType<
  StepCreateDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  type: StepTypeEnum$inboundSchema,
  controlValues: z.nullable(z.record(z.any())).optional(),
});

/** @internal */
export type StepCreateDto$Outbound = {
  name: string;
  type: string;
  controlValues?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const StepCreateDto$outboundSchema: z.ZodType<
  StepCreateDto$Outbound,
  z.ZodTypeDef,
  StepCreateDto
> = z.object({
  name: z.string(),
  type: StepTypeEnum$outboundSchema,
  controlValues: z.nullable(z.record(z.any())).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StepCreateDto$ {
  /** @deprecated use `StepCreateDto$inboundSchema` instead. */
  export const inboundSchema = StepCreateDto$inboundSchema;
  /** @deprecated use `StepCreateDto$outboundSchema` instead. */
  export const outboundSchema = StepCreateDto$outboundSchema;
  /** @deprecated use `StepCreateDto$Outbound` instead. */
  export type Outbound = StepCreateDto$Outbound;
}

export function stepCreateDtoToJSON(stepCreateDto: StepCreateDto): string {
  return JSON.stringify(StepCreateDto$outboundSchema.parse(stepCreateDto));
}

export function stepCreateDtoFromJSON(
  jsonString: string,
): SafeParseResult<StepCreateDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StepCreateDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StepCreateDto' from JSON`,
  );
}
