/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  StepTypeEnum,
  StepTypeEnum$inboundSchema,
  StepTypeEnum$outboundSchema,
} from "./steptypeenum.js";

export type StepUpdateDto = {
  /**
   * Name of the step
   */
  name: string;
  /**
   * Type of the step
   */
  type: StepTypeEnum;
  /**
   * Control values for the step
   */
  controlValues?: { [k: string]: any } | null | undefined;
  /**
   * Unique identifier of the step
   */
  id: string;
};

/** @internal */
export const StepUpdateDto$inboundSchema: z.ZodType<
  StepUpdateDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  type: StepTypeEnum$inboundSchema,
  controlValues: z.nullable(z.record(z.any())).optional(),
  _id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "_id": "id",
  });
});

/** @internal */
export type StepUpdateDto$Outbound = {
  name: string;
  type: string;
  controlValues?: { [k: string]: any } | null | undefined;
  _id: string;
};

/** @internal */
export const StepUpdateDto$outboundSchema: z.ZodType<
  StepUpdateDto$Outbound,
  z.ZodTypeDef,
  StepUpdateDto
> = z.object({
  name: z.string(),
  type: StepTypeEnum$outboundSchema,
  controlValues: z.nullable(z.record(z.any())).optional(),
  id: z.string(),
}).transform((v) => {
  return remap$(v, {
    id: "_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StepUpdateDto$ {
  /** @deprecated use `StepUpdateDto$inboundSchema` instead. */
  export const inboundSchema = StepUpdateDto$inboundSchema;
  /** @deprecated use `StepUpdateDto$outboundSchema` instead. */
  export const outboundSchema = StepUpdateDto$outboundSchema;
  /** @deprecated use `StepUpdateDto$Outbound` instead. */
  export type Outbound = StepUpdateDto$Outbound;
}

export function stepUpdateDtoToJSON(stepUpdateDto: StepUpdateDto): string {
  return JSON.stringify(StepUpdateDto$outboundSchema.parse(stepUpdateDto));
}

export function stepUpdateDtoFromJSON(
  jsonString: string,
): SafeParseResult<StepUpdateDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StepUpdateDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StepUpdateDto' from JSON`,
  );
}
