/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PreferencesRequestDto,
  PreferencesRequestDto$inboundSchema,
  PreferencesRequestDto$Outbound,
  PreferencesRequestDto$outboundSchema,
} from "./preferencesrequestdto.js";
import {
  StepCreateDto,
  StepCreateDto$inboundSchema,
  StepCreateDto$Outbound,
  StepCreateDto$outboundSchema,
} from "./stepcreatedto.js";
import {
  StepUpdateDto,
  StepUpdateDto$inboundSchema,
  StepUpdateDto$Outbound,
  StepUpdateDto$outboundSchema,
} from "./stepupdatedto.js";
import {
  WorkflowOriginEnum,
  WorkflowOriginEnum$inboundSchema,
  WorkflowOriginEnum$outboundSchema,
} from "./workfloworiginenum.js";

export type Steps = StepCreateDto | StepUpdateDto;

export type UpdateWorkflowDto = {
  /**
   * Name of the workflow
   */
  name: string;
  /**
   * Description of the workflow
   */
  description?: string | undefined;
  /**
   * Tags associated with the workflow
   */
  tags?: Array<string> | undefined;
  /**
   * Whether the workflow is active
   */
  active?: boolean | undefined;
  /**
   * Workflow ID (allowed only for code-first workflows)
   */
  workflowId?: string | undefined;
  /**
   * Steps of the workflow
   */
  steps: Array<StepCreateDto | StepUpdateDto>;
  /**
   * Workflow preferences
   */
  preferences: PreferencesRequestDto;
  /**
   * Origin of the workflow
   */
  origin: WorkflowOriginEnum;
};

/** @internal */
export const Steps$inboundSchema: z.ZodType<Steps, z.ZodTypeDef, unknown> = z
  .union([StepCreateDto$inboundSchema, StepUpdateDto$inboundSchema]);

/** @internal */
export type Steps$Outbound = StepCreateDto$Outbound | StepUpdateDto$Outbound;

/** @internal */
export const Steps$outboundSchema: z.ZodType<
  Steps$Outbound,
  z.ZodTypeDef,
  Steps
> = z.union([StepCreateDto$outboundSchema, StepUpdateDto$outboundSchema]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Steps$ {
  /** @deprecated use `Steps$inboundSchema` instead. */
  export const inboundSchema = Steps$inboundSchema;
  /** @deprecated use `Steps$outboundSchema` instead. */
  export const outboundSchema = Steps$outboundSchema;
  /** @deprecated use `Steps$Outbound` instead. */
  export type Outbound = Steps$Outbound;
}

export function stepsToJSON(steps: Steps): string {
  return JSON.stringify(Steps$outboundSchema.parse(steps));
}

export function stepsFromJSON(
  jsonString: string,
): SafeParseResult<Steps, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Steps$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Steps' from JSON`,
  );
}

/** @internal */
export const UpdateWorkflowDto$inboundSchema: z.ZodType<
  UpdateWorkflowDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  description: z.string().optional(),
  tags: z.array(z.string()).optional(),
  active: z.boolean().default(false),
  workflowId: z.string().optional(),
  steps: z.array(
    z.union([StepCreateDto$inboundSchema, StepUpdateDto$inboundSchema]),
  ),
  preferences: PreferencesRequestDto$inboundSchema,
  origin: WorkflowOriginEnum$inboundSchema,
});

/** @internal */
export type UpdateWorkflowDto$Outbound = {
  name: string;
  description?: string | undefined;
  tags?: Array<string> | undefined;
  active: boolean;
  workflowId?: string | undefined;
  steps: Array<StepCreateDto$Outbound | StepUpdateDto$Outbound>;
  preferences: PreferencesRequestDto$Outbound;
  origin: string;
};

/** @internal */
export const UpdateWorkflowDto$outboundSchema: z.ZodType<
  UpdateWorkflowDto$Outbound,
  z.ZodTypeDef,
  UpdateWorkflowDto
> = z.object({
  name: z.string(),
  description: z.string().optional(),
  tags: z.array(z.string()).optional(),
  active: z.boolean().default(false),
  workflowId: z.string().optional(),
  steps: z.array(
    z.union([StepCreateDto$outboundSchema, StepUpdateDto$outboundSchema]),
  ),
  preferences: PreferencesRequestDto$outboundSchema,
  origin: WorkflowOriginEnum$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateWorkflowDto$ {
  /** @deprecated use `UpdateWorkflowDto$inboundSchema` instead. */
  export const inboundSchema = UpdateWorkflowDto$inboundSchema;
  /** @deprecated use `UpdateWorkflowDto$outboundSchema` instead. */
  export const outboundSchema = UpdateWorkflowDto$outboundSchema;
  /** @deprecated use `UpdateWorkflowDto$Outbound` instead. */
  export type Outbound = UpdateWorkflowDto$Outbound;
}

export function updateWorkflowDtoToJSON(
  updateWorkflowDto: UpdateWorkflowDto,
): string {
  return JSON.stringify(
    UpdateWorkflowDto$outboundSchema.parse(updateWorkflowDto),
  );
}

export function updateWorkflowDtoFromJSON(
  jsonString: string,
): SafeParseResult<UpdateWorkflowDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateWorkflowDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateWorkflowDto' from JSON`,
  );
}
